### ISSUE TITLE
The controls of the Maps pannel are not being loaded

### ISSUE THREAD

**Issue by dfarache** [cobi-bike/DevKit-Simulator#29]
Looks like it's a CSP issue

![screen shot 2018-08-27 at 09 56 33](https://user-images.githubusercontent.com/5766203/44647880-aa9cbd00-a9df-11e8-9f3b-39da72ab0ffa.png)

![screen shot 2018-08-27 at 09 58 31](https://user-images.githubusercontent.com/5766203/44647932-ce600300-a9df-11e8-9276-a56b21258702.png)

**Comment by carocad** [comment]
@dfarache I think this is because of content security rules. Maybe this helps:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src
- https://stackoverflow.com/questions/33984908/google-fonts-violates-content-security-policy

You might also need to enable some style-src csp for that though

**Comment by dfarache** [comment]
Indeed, style-src and image-src have to be enabled for google maps

**Comment by dfarache** [comment]
fixed by #30
